### ISSUE TITLE
火狐浏览器插件

### ISSUE THREAD

**Issue by chichi1314520** [woniu9524/dingdang-extension#14]
未来有对火狐浏览器支持的打算吗？

**Comment by woniu9524** [comment]
看情况吧，如果这个项目用的人多的话会进行后续的开发，包括插件小程序的优化，火狐的支持，甚至移动端的支持都在考虑范围内，目前只是简单的demo，因为没人用，所以emmm后续就随缘开发了。

**Comment by woniu9524** [comment]
目前优先解决bug，和功能上的不足，如果有这方面的可以提

**Comment by chichi1314520** [comment]
<img width="1280" alt="ab05ab19842250203d8919928feee85" src="https://github.com/woniu9524/dingdang-extension/assets/42328109/aea291bf-54f1-4dbb-9833-93c1bbf9fce1">
<img width="1280" alt="886fb3532345ccada742fcf8478915e" src="https://github.com/woniu9524/dingdang-extension/assets/42328109/d04d4272-db1e-4a1f-87b2-8c41053d24e8">
我是在edge和chrom的插件市场下载的，都没有反应啊

**Comment by woniu9524** [comment]
你有没有选词书呢，你可以加我qq 952490637 具体说说
